### PR TITLE
Another case of bad markup identified in Issue#549. Closing tags without having opening tags. Test cases also added.

### LINKED ISSUE #549: It is possible to add a disallowed closing tag with valid HTML as well as opening tag with invalid HTML markup.
I found several variants of the library's incorrect behavior. In the examples below, it is possible to add any html tag (closing tag with valid HTML as well as opening tag with invalid HTML) if any tag is allowed.

## Example 1:

```
const sanitizeHtml = require('sanitize-html');

const sanitizedString = sanitizeHtml('<b><div/', {
    allowedTags: ['b'],
});
```

## Example 2:

```
const sanitizeHtml = require('sanitize-html');
const HTMLParser = require('node-html-parser');

const sanitizedString = sanitizeHtml('<b><b<<div/', {
    allowedTags: ['b'],
});

console.log(sanitizedString) // <b></b<<div>

const unespectedDiv = HTMLParser.parse(sanitizedString).querySelector('div');

console.log(unespectedDiv);
```

### PR DESCRIPTION
**Pull request by kedarchandrayan**
## Summary

Closes #549 

## What are the specific steps to test this change?
The snippets given in the issues should now work as expected.

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [x] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by kedarchandrayan** [comment]
Hello Team,
cc: @boutell 

Please review this change and let me know what needs to be changed.

Thanks in advance!
Kedar Chandrayan

**Review by boutell — CHANGES_REQUESTED** [review]
I think the current code tolerates markup like this:

```
<div>
<p>
<p>
<p>
</div>
```

I think your change would break that which is too strict (a backwards compatibility break). Please add unit tests confirming if you think it won't be a problem.

Also:

```
<div>
<br />
<br />
<br />
</div>
```

I'm not sure if these self-closing tags go on the stack or not.

**Comment by kedarchandrayan** [comment]
Hello @boutell, 

Thank you for the feedback. Following is my response, point-wise.

Markup like the following works fine, even after the change. `htmlparser2` gives callbacks for both onopentag and onclosetag for the p tags, even if the closing p tags are not present.

```
<div>
<p>
<p>
<p>
</div>
```

I have added 2 test cases for the above markup as asked by you.

For self-closing tags, `htmlparser2` gives consecutive callbacks for onopentag and onclosetag. In these the tag goes in the stack and gets popped immediately. So these will also work with the change made.

Thanks again for the feedback. Please let me know if anything else is needed from my end.

**Review by boutell — APPROVED** [review]

**Comment by boutell** [comment]
Thanks!

**Comment by kedarchandrayan** [comment]
Thank you @boutell 🙏

**Pull request merged**
