### PR TITLE
Allow text transform with function

### PR DESCRIPTION
**Pull request by bonkzwonil**
allow transformTags to return a function for transforming text

### CODE REVIEW

**Comment by bonkzwonil** [comment]
Pull Request that you can specify a function for transforming/processing innerText:

```js
 clean = sanitizeHtml(dirty, {
   transformTags: {
     'style': function(tagName, attribs) {
         return {
             tagName: tagName,
             attribs: attribs,
             text: function(text){
 			    return myCssTransform(text);
 			}
         };
     }
  }
 +});

**Comment by hoanguyen311** [comment]
that's what I need

**Comment by hoanguyen311** [comment]
Is this one an altenative ?
``` clean = sanitizeHtml(dirty, {
   transformTags: {
     'style': function(tagName, attribs, text) {
         return {
             tagName: tagName,
             attribs: attribs,
             text: myCssTransform(text)
           
         };
     }
  }
});
```

**Comment by anowell** [comment]
I'd like to see the latter suggestion by @hoanguyen311 }. Specifically I'm looking to use it to transform:

`<h2>Foo</h2>` into `<h2 id="foo">Foo</h2>` with something like this:

```
transformTags: {
     'h2': function(tagName, attribs, text) {
         return {
             tagName: tagName,
             attribs: { id: slugify(text) },
             text: text
         };
     }
}
```

**Comment by graingert** [comment]
Probably makes more sense in something like trumpet

**Comment by Worie** [comment]
what's up with this one? That'd be hella handy :)

**Comment by boutell** [comment]
The proposed syntax by @hoanguyen311 makes more sense to me, unless it would be difficult to implement — what do you think @bonkzwonil?

Also please follow the coding style when submitting PRs, two spaces, no tabs, and add unit tests.

**Comment by abea** [comment]
At this point it could be merged into the 2.x version (`v2` branch) instead.

**Comment by graingert** [comment]
Bump

**Comment by abea** [comment]
@graingert It's been unchanged for years now, so I don't think a bump comment is helpful. You may need to pick this up to close out if you'd like to see it completed.

**Comment by graingert** [comment]
@abea the bot asked me to bump it so I did.

**Pull request closed without merging**
