### PR TITLE
Parse srcset

### LINKED ISSUE #367: Dependency mangles srcset img attribute
## To Reproduce

Run the following test:

```js
  it('should accept srcset urls matching spec', function() {
    assert.equal(
      sanitizeHtml('<img src="fallback.jpg" srcset="/upload/f_auto,q_auto:eco,c_fit,w_1460,h_2191/abc.jpg 1460w,/upload/f_auto,q_auto:eco,c_fit,w_1360,h_2041/abc.jpg" />', {
        allowedTags: sanitizeHtml.defaults.allowedTags.concat([ 'img' ]),
        allowedAttributes: { img: [ 'src', 'srcset' ] }
      }),
      '<img src="fallback.jpg" srcset="/upload/f_auto,q_auto:eco,c_fit,w_1460,h_2191/abc.jpg 1460w,/upload/f_auto,q_auto:eco,c_fit,w_1360,h_2041/abc.jpg" />'
    );
  }); 
```

## Expected behavior

Test  should pass.

## Describe the bug

Test fails with:

```
      AssertionError [ERR_ASSERTION]: '<img src="fallback.jpg" srcset="/upload/f_auto, q_auto:eco, c_fit, w_1460, h_2191/abc.jpg 1460w, w_1360, h_2041/abc.jpg" />' == '<img src="fallback.jpg" srcset="/upload/f_auto,q_auto:eco,c_fit,w_1460,h_2191/abc.jpg 1460w,/upload/f_auto,q_auto:eco,c_fit,w_1360,h_2041/abc.jpg" />'
      + expected - actual

      -<img src="fallback.jpg" srcset="/upload/f_auto, q_auto:eco, c_fit, w_1460, h_2191/abc.jpg 1460w, w_1360, h_2041/abc.jpg" />
      +<img src="fallback.jpg" srcset="/upload/f_auto,q_auto:eco,c_fit,w_1460,h_2191/abc.jpg 1460w,/upload/f_auto,q_auto:eco,c_fit,w_1360,h_2041/abc.jpg" />
```

## Details

**Version of Node.js:** 12.17.0
**Server Operating System:** Arch Linux

**Additional context:**

The culprit is https://github.com/sindresorhus/srcset/issues/1

[Prettier](https://github.com/prettier/prettier) solved it by switching (back) to [parse-srcset](https://github.com/albell/parse-srcset) in https://github.com/prettier/prettier/issues/8150. `parse-srcset` is [tested](https://github.com/albell/parse-srcset/blob/master/tests/unit/ps.js) against actual w3c specs.

### PR DESCRIPTION
**Pull request by abea**
Completes #368
Resolves #367

### CODE REVIEW

**Comment by TrySound** [comment]
Is this v1 only change?

**Comment by abea** [comment]
It is. We'll be release 2.x as a beta, so this could be ported into 2.x in the next release.

**Comment by TrySound** [comment]
But didn't my upgrade PR solved the problem?
https://github.com/apostrophecms/sanitize-html/pull/386

**Comment by TrySound** [comment]
Hm.. I see srcset is very loose parser

**Comment by abea** [comment]
It seems that way, yes.

**Pull request merged**
