### PR TITLE
Fix auto-adding escaped closing tags

### LINKED ISSUE #464: Escaping input with unclosed, invalid tags returns it with unneeded escaped closing tags appended to end
## To Reproduce

From the Node REPL:
```
> const s = require('sanitize-html')
undefined
> s("here's a string with a <wacky> tag.", {disallowedTagsMode: "escape"})
"here's a string with a &lt;wacky&gt; tag.&lt;/wacky&gt;"
```

## Expected behavior

The offending tag is escaped, but no addition markup is created. For example, given the input `here's a string with a <wacky> tag`, I would expect the output to be: `here's a string with a &lt;wacky&gt; tag`

## Describe the bug

When sanitizing a string with `disallowedTagsMode: "escape"`, extra, unneeded (escaped) closing tags are appended to the end of the string.

## Details

**Version of Node.js:** 15.5.0
**Server Operating System:** Ubuntu 20.04

### PR DESCRIPTION
**Pull request by dliebner**
## Summary

Closes #464 
Adds `tagAllowed()` helper function.

## What are the specific steps to test this change?

Existing tests may need to be reviewed. I don't do a lot of PRs, sorry.

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [x] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by BoDonkey** [comment]
Hi @dliebner 
Thanks for giving this a go! As a first step, can you at least describe how your new function should work? Does the `tagAllowed()` take a boolean, or...? You can use the original example to provide the input and expected output. "<p>here is a string with a <wacky> tag.</p>"
Thanks!
Bob

**Comment by dliebner** [comment]
`tagAllowed()` takes a tag name and checks it against `options.allowedTags` and returns `true` if the tag is allowed and `false` if it is not.

```
const wackyText = sanitizeHtml('<p>here\'s a string with a <wacky> tag.', {
	disallowedTagsMode: 'escape',
});
  
console.log( wackyText ); // expected: "<p>here's a string with a &lt;wacky&gt; tag.</p>"
```

**Comment by BoDonkey** [comment]
Hi @dliebner,
I'm still not quite getting it. I wrote the following test:
```
it('Should allow unclosed tags', function() {
    assert.equal(
      sanitizeHtml('<p>Text with a <wacky> tag.</p>', {
        allowedTags: [ 'wacky' ],
        disallowedTagsMode: 'escape'
      }), '<p>Text with a <wacky> tag.</p>'
    );
  });
```
This test fails with the output being: `&lt;p&gt;Text with a <wacky> tag.</wacky>&lt;/p&gt;`
While I expected: `&lt;p&gt;Text with a &lt;wacky&gt; tag.&lt;/p&gt;` based on the original issue.
Any additional feedback?
Thanks,
Bob

**Comment by dliebner** [comment]
In your test, you set your `allowedTags` to `['wacky']`, meaning only the `wacky` tag is allowed. All other tags will be escaped using HTML entities.  The opening `<p>` is correctly sanitized as it is not allowed. The opening `<wacky>` tag is correctly preserved as it is allowed, and it is correctly auto-closed as it is allowed. The closing `</p>` tag is correctly sanitized because it is not allowed (and is literally included in the input, as opposed to being only implied by the presence of an opening tag).

**Review by BoDonkey — CHANGES_REQUESTED** [review]
Now I understand the functionality. Thanks! Can you update your PR with a test in the `/test/test.js` file? It can essentially be the test that I wrote, but please add a better descriptive sentence. Can you also update the `CHANGELOG.md` file, please? At the top add a section called 'UNRELEASED' and then a description of your change.

**Review by BoDonkey — CHANGES_REQUESTED** [review]
Thanks for making the changes. We are almost there! 
Two items:
1) If you give the command `npm run test`, it will fail due to linting code errors. Please fix the ones you introduced.
2) While your tests are passing, if the first or second ones were to fail, we wouldn't have proper notification since they are combined together in a single `it()`. Please separate these into two test statements.
Sorry to nitpick and thanks for doing this.

**Review by BoDonkey — APPROVED** [review]
Thanks for the changes! It looks good, but today is a release day, so I won't merge it until tomorrow. The changes will be published on our next release day, which is Feb. 15.

**Pull request merged**
